"""m25_stats period unit not null empty default

Revision ID: 6060da89549d
Revises: 827106eec8f4
Create Date: 2026-09-13 03:38:30.151637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6060da89549d'
down_revision: Union[str, Sequence[str], None] = '827106eec8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    历史数据修复（非自动生成，手写）：此前 `period`/`unit` 为 NULL 时，MySQL 唯一索引
    `uq_m25_dedupe` 对 NULL 值不去重，导致 S01/S05/S09/S10/S11（unit 恒为 NULL）以及
    S10/S11（period 也恒为 NULL）每次轮询/回填都插入新行而不是覆盖旧值（已实测复现：
    约 3 万组重复行）。升级步骤：
    1) 先删除唯一索引——否则把 NULL 规范化为 `''` 时会与已存在的同键 `''` 行立刻冲突；
    2) 把 NULL 规范化为空字符串 `''`；
    3) 按新去重键 (metric, query_key, period, unit, ts_ms) 只保留每组 id 最大的一行；
    4) 改列为 NOT NULL；
    5) 重建唯一索引。
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_m25_dedupe', 'm25_stats', type_='unique')
    op.execute("UPDATE m25_stats SET period = '' WHERE period IS NULL")
    op.execute("UPDATE m25_stats SET unit = '' WHERE unit IS NULL")
    op.execute(
        """
        DELETE t1 FROM m25_stats t1
        INNER JOIN m25_stats t2
          ON t1.metric = t2.metric
         AND t1.query_key = t2.query_key
         AND t1.period = t2.period
         AND t1.unit = t2.unit
         AND t1.ts_ms = t2.ts_ms
         AND t1.id < t2.id
        """
    )
    op.alter_column('m25_stats', 'period',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
    op.alter_column('m25_stats', 'unit',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.create_unique_constraint(
        'uq_m25_dedupe', 'm25_stats', ['metric', 'query_key', 'period', 'unit', 'ts_ms']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    注意：无法恢复升级时删除的重复行；仅恢复列的可空性，不把 `''` 还原为 NULL
    （降级路径不追求语义完全对称，只保证 schema 可回退）。
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m25_stats', 'unit',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('m25_stats', 'period',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###
