"""add trades and extended candles

Revision ID: 827106eec8f4
Revises: db01090c5c59
Create Date: 2026-09-12 23:52:33.219483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827106eec8f4'
down_revision: Union[str, Sequence[str], None] = 'db01090c5c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m03_public_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('px', sa.String(length=64), nullable=False),
    sa.Column('sz', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('count', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('seq_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'trade_id', name='uq_m03_inst_trade')
    )
    op.create_index('ix_m03_inst_ts', 'm03_public_trades', ['inst_id', 'ts_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_m03_inst_ts', table_name='m03_public_trades')
    op.drop_table('m03_public_trades')
    # ### end Alembic commands ###
