"""init schema

Revision ID: db01090c5c59
Revises: 
Create Date: 2026-09-12 22:01:27.444106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db01090c5c59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('TRADE', 'MARK', name='candlekind'), nullable=False),
    sa.Column('bar', sa.String(length=8), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('o', sa.String(length=64), nullable=False),
    sa.Column('h', sa.String(length=64), nullable=False),
    sa.Column('l', sa.String(length=64), nullable=False),
    sa.Column('c', sa.String(length=64), nullable=False),
    sa.Column('vol', sa.String(length=64), nullable=True),
    sa.Column('vol_ccy', sa.String(length=64), nullable=True),
    sa.Column('vol_ccy_quote', sa.String(length=64), nullable=True),
    sa.Column('confirm', sa.String(length=4), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'kind', 'bar', 'ts_ms', name='uq_candle_key')
    )
    op.create_index('ix_candle_lookup', 'candles', ['inst_id', 'kind', 'bar', 'ts_ms'], unique=False)
    op.create_table('instrument_catalog_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('base_ccy', sa.String(length=32), nullable=True),
    sa.Column('quote_ccy', sa.String(length=32), nullable=True),
    sa.Column('settle_ccy', sa.String(length=32), nullable=True),
    sa.Column('ct_type', sa.String(length=16), nullable=True),
    sa.Column('inst_family', sa.String(length=64), nullable=True),
    sa.Column('uly', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instrument_catalog_current', 'instrument_catalog_versions', ['inst_type', 'inst_id', 'is_current'], unique=False)
    op.create_table('m01_ticker_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('last', sa.String(length=64), nullable=True),
    sa.Column('last_sz', sa.String(length=64), nullable=True),
    sa.Column('bid_px', sa.String(length=64), nullable=True),
    sa.Column('bid_sz', sa.String(length=64), nullable=True),
    sa.Column('ask_px', sa.String(length=64), nullable=True),
    sa.Column('ask_sz', sa.String(length=64), nullable=True),
    sa.Column('open24h', sa.String(length=64), nullable=True),
    sa.Column('high24h', sa.String(length=64), nullable=True),
    sa.Column('low24h', sa.String(length=64), nullable=True),
    sa.Column('vol_ccy24h', sa.String(length=64), nullable=True),
    sa.Column('vol24h', sa.String(length=64), nullable=True),
    sa.Column('sod_utc0', sa.String(length=64), nullable=True),
    sa.Column('sod_utc8', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m01_inst_ts')
    )
    op.create_index(op.f('ix_m01_ticker_snapshots_inst_id'), 'm01_ticker_snapshots', ['inst_id'], unique=False)
    op.create_table('m05_book5_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('asks', sa.JSON(), nullable=False),
    sa.Column('bids', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m05_inst_ts')
    )
    op.create_index(op.f('ix_m05_book5_snapshots_inst_id'), 'm05_book5_snapshots', ['inst_id'], unique=False)
    op.create_table('m10_mark_price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('mark_px', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m10_inst_ts')
    )
    op.create_index(op.f('ix_m10_mark_price_snapshots_inst_id'), 'm10_mark_price_snapshots', ['inst_id'], unique=False)
    op.create_table('m12_funding_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('funding_rate', sa.String(length=64), nullable=True),
    sa.Column('funding_time', sa.BigInteger(), nullable=True),
    sa.Column('next_funding_time', sa.BigInteger(), nullable=True),
    sa.Column('sett_state', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m12_inst_ts')
    )
    op.create_index(op.f('ix_m12_funding_rates_inst_id'), 'm12_funding_rates', ['inst_id'], unique=False)
    op.create_table('m13_open_interest_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.String(length=64), nullable=True),
    sa.Column('oi_ccy', sa.String(length=64), nullable=True),
    sa.Column('oi_usd', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m13_inst_ts')
    )
    op.create_index(op.f('ix_m13_open_interest_snapshots_inst_id'), 'm13_open_interest_snapshots', ['inst_id'], unique=False)
    op.create_table('m14_price_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.String(length=8), nullable=True),
    sa.Column('buy_lmt', sa.String(length=64), nullable=True),
    sa.Column('sell_lmt', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m14_inst_ts')
    )
    op.create_index(op.f('ix_m14_price_limits_inst_id'), 'm14_price_limits', ['inst_id'], unique=False)
    op.create_table('m15_estimated_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('inst_type', sa.String(length=16), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('settle_type', sa.String(length=16), nullable=True),
    sa.Column('settle_px', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'ts_ms', name='uq_m15_inst_ts')
    )
    op.create_index(op.f('ix_m15_estimated_prices_inst_id'), 'm15_estimated_prices', ['inst_id'], unique=False)
    op.create_table('m16_risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('LIQUIDATION', 'ADL_WARNING', name='riskeventtype'), nullable=False),
    sa.Column('business_ts', sa.BigInteger(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'event_type', 'business_ts', 'payload_hash', name='uq_m16_dedupe')
    )
    op.create_index(op.f('ix_m16_risk_events_inst_id'), 'm16_risk_events', ['inst_id'], unique=False)
    op.create_table('m22_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('business_ts', sa.BigInteger(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inst_id', 'business_ts', 'payload_hash', name='uq_m22_revision')
    )
    op.create_index(op.f('ix_m22_revisions_inst_id'), 'm22_revisions', ['inst_id'], unique=False)
    op.create_table('m22_series',
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('freq', sa.String(length=32), nullable=True),
    sa.Column('settlement', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('m23_economic_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('actual', sa.String(length=64), nullable=True),
    sa.Column('forecast', sa.String(length=64), nullable=True),
    sa.Column('previous', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'ts_ms', name='uq_m23_dedupe')
    )
    op.create_index(op.f('ix_m23_economic_calendar_calendar_id'), 'm23_economic_calendar', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_m23_economic_calendar_date'), 'm23_economic_calendar', ['date'], unique=False)
    op.create_table('m25_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric', sa.Enum('S01', 'S04', 'S05', 'S09', 'S10', 'S11', name='m25metric'), nullable=False),
    sa.Column('query_key', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=True),
    sa.Column('unit', sa.String(length=4), nullable=True),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('site', sa.String(length=16), server_default='okex', nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric', 'query_key', 'period', 'unit', 'ts_ms', name='uq_m25_dedupe')
    )
    op.create_index('ix_m25_lookup', 'm25_stats', ['metric', 'query_key', 'period', 'unit', 'ts_ms'], unique=False)
    op.create_table('m25_unit_preferences',
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=4), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('inst_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('m22_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('exp_time', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['m22_series.series_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('subscription_config_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ordered_inst_ids', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_active_inst_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('m22_markets',
    sa.Column('inst_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('list_time', sa.BigInteger(), nullable=True),
    sa.Column('fix_time', sa.BigInteger(), nullable=True),
    sa.Column('exp_time', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('floor_strike', sa.String(length=64), nullable=True),
    sa.Column('cap_strike', sa.String(length=64), nullable=True),
    sa.Column('settle_value', sa.String(length=64), nullable=True),
    sa.Column('disputed', sa.String(length=16), nullable=True),
    sa.Column('hit_dir', sa.String(length=16), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['m22_events.event_id'], ),
    sa.PrimaryKeyConstraint('inst_id')
    )
    op.create_index(op.f('ix_m22_markets_exp_time'), 'm22_markets', ['exp_time'], unique=False)
    op.create_index(op.f('ix_m22_markets_series_id'), 'm22_markets', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m22_markets_series_id'), table_name='m22_markets')
    op.drop_index(op.f('ix_m22_markets_exp_time'), table_name='m22_markets')
    op.drop_table('m22_markets')
    op.drop_table('user_preferences')
    op.drop_table('subscription_config_versions')
    op.drop_table('m22_events')
    op.drop_table('users')
    op.drop_table('m25_unit_preferences')
    op.drop_index('ix_m25_lookup', table_name='m25_stats')
    op.drop_table('m25_stats')
    op.drop_index(op.f('ix_m23_economic_calendar_date'), table_name='m23_economic_calendar')
    op.drop_index(op.f('ix_m23_economic_calendar_calendar_id'), table_name='m23_economic_calendar')
    op.drop_table('m23_economic_calendar')
    op.drop_table('m22_series')
    op.drop_index(op.f('ix_m22_revisions_inst_id'), table_name='m22_revisions')
    op.drop_table('m22_revisions')
    op.drop_index(op.f('ix_m16_risk_events_inst_id'), table_name='m16_risk_events')
    op.drop_table('m16_risk_events')
    op.drop_index(op.f('ix_m15_estimated_prices_inst_id'), table_name='m15_estimated_prices')
    op.drop_table('m15_estimated_prices')
    op.drop_index(op.f('ix_m14_price_limits_inst_id'), table_name='m14_price_limits')
    op.drop_table('m14_price_limits')
    op.drop_index(op.f('ix_m13_open_interest_snapshots_inst_id'), table_name='m13_open_interest_snapshots')
    op.drop_table('m13_open_interest_snapshots')
    op.drop_index(op.f('ix_m12_funding_rates_inst_id'), table_name='m12_funding_rates')
    op.drop_table('m12_funding_rates')
    op.drop_index(op.f('ix_m10_mark_price_snapshots_inst_id'), table_name='m10_mark_price_snapshots')
    op.drop_table('m10_mark_price_snapshots')
    op.drop_index(op.f('ix_m05_book5_snapshots_inst_id'), table_name='m05_book5_snapshots')
    op.drop_table('m05_book5_snapshots')
    op.drop_index(op.f('ix_m01_ticker_snapshots_inst_id'), table_name='m01_ticker_snapshots')
    op.drop_table('m01_ticker_snapshots')
    op.drop_index('ix_instrument_catalog_current', table_name='instrument_catalog_versions')
    op.drop_table('instrument_catalog_versions')
    op.drop_index('ix_candle_lookup', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
